apiVersion: v1
kind: Service
metadata:
  annotations:
  name: devops-scaler-loadrun
  namespace: sit
spec:
  clusterIP: None
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    k8s-app: devops-scaler-loadrun
  sessionAffinity: None
  type: ClusterIP
